---
kind: pipeline
type: docker
name: raspbian-arm-1

platform:
  os: linux
  arch: arm

steps:
  - name: stretch
    image: balenalib/raspberry-pi-debian:stretch
    environment: 
      OCPN_TARGET: stretch-armhf
    environment: 
      CLOUDSMITH_API_KEY:
        from_secret: CLOUDSMITH_API_KEY
      CLOUDSMITH_STABLE_REPO:
        from_secret: CLOUDSMITH_STABLE_REPO
      CLOUDSMITH_UNSTABLE_REPO:
        from_secret: CLOUDSMITH_UNSTABLE_REPO
      CLOUDSMITH_BETA_REPO:
        from_secret: CLOUDSMITH_BETA_REPO
      GIT_REPO:
        from_secret: GIT_REPO
      GIT_KEY_PASSWORD:
        from_secret: GIT_KEY_PASSWORD
    commands:
      - export PATH=$HOME/.local/bin:$PATH
      - /bin/bash ci/drone-build-raspbian.sh
      - bash -c "cd build; bash < upload.sh"
      - python3 ci/git-push

---
kind: pipeline
type: docker
name: raspbian-arm-2

platform:
  os: linux
  arch: arm

steps:
  - name: buster
    image: balenalib/raspberry-pi-debian:buster
    environment: 
      OCPN_TARGET: buster-armhf
    environment: 
      CLOUDSMITH_API_KEY:
        from_secret: CLOUDSMITH_API_KEY
      CLOUDSMITH_STABLE_REPO:
        from_secret: CLOUDSMITH_STABLE_REPO
      CLOUDSMITH_UNSTABLE_REPO:
        from_secret: CLOUDSMITH_UNSTABLE_REPO
      CLOUDSMITH_BETA_REPO:
        from_secret: CLOUDSMITH_BETA_REPO
      GIT_REPO:
        from_secret: GIT_REPO
      GIT_KEY_PASSWORD:
        from_secret: GIT_KEY_PASSWORD
    commands:
      - export PATH=$HOME/.local/bin:$PATH
      - ci/drone-build-raspbian.sh
      - bash -c "cd build; bash < upload.sh"
      - python3 ci/git-push
